---
title: "Servicios ecosistémicos del Corredor Biológico Interurbano Río Torres"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leaflet.opacity)
library(leafem)
library(esri2sf)
library(raster)
library(plotly)

#--------------- URL de geoservicios y archivos de datos --------------

url_agfs_limite_cbirt <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_cbi_rio_torres/FeatureServer/0"

url_raster_infraestructura_natural_gris <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-infraestructura-verde/master/cbirt/IV_CBI_RIO_TORRES_INFNATGRIS_WEB.TIF"

#--------------- Objetos sf y raster ---------------

# Límite del CBIRT
sf_limite_cbirt <- 
  esri2sf(url_agfs_limite_cbirt)

# Límite del CBIRT (reproyectado a Web Mercator)
sf_limite_cbirt_web <- 
  sf_limite_cbirt %>%
  st_transform(3857)

# Capa raster de infraestructura natural y gris (en Web Mercator)
raster_infraestructura_natural_gris <-
  raster(url_raster_infraestructura_natural_gris) %>%
  aggregate(fact=c(2), fun=modal) %>% # ¡¡HAY QUE TRATAR DE ELIMINAR ESTA AGRUPACIÓN. PODRÍA FUNCIONAR AL USAR MÁS MEMORIA LINUX!!
  crop(sf_limite_cbirt_web) %>%
  mask(sf_limite_cbirt_web)

#---------------- Paletas de colores ---------------

colores_infraestructura_natural_gris <- 
  c(rgb(43,99,89,    maxColorValue=255),
    rgb(204,204,204, maxColorValue=255))

etiquetas_infraestructura_natural_gris <- 
  c("Natural", 
    "Gris"
    )

values_infraestructura_natural_gris <- 
  c(100,
    200)

pal_infraestructura_natural_gris <- 
  colorFactor(
    palette = colores_infraestructura_natural_gris, 
    domain = values_infraestructura_natural_gris,
    na.color = "transparent"
  )

```


Row {data-height=600}
-----------------------------------------------------------------------

### {data-width=650}
```{r}

#------------------- Mapa ------------------

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_cbirt,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite del CBIRT"
  ) %>%
  addRasterImage(
    raster_infraestructura_natural_gris,
    layerId = "raster",    
    colors = pal_infraestructura_natural_gris,
    opacity = 1,
    group = "Infraestructura"
  ) %>%
  addLegend(
    title = "Infraestructura",
    position = "bottomright",
    colors = colores_infraestructura_natural_gris,
    labels = etiquetas_infraestructura_natural_gris,
    group = "Infraestructura"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "CartoDB Dark Matter", "Imágenes de ESRI"),
    overlayGroups = c("Límite del CBIRT", "Infraestructura"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    minimized = FALSE,
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates() %>%
  addSearchOSM() %>%
  addResetMapButton() %>%
  addOpacitySlider(layerId = "raster")
```

### {data-width=350}
```{r}

# Vector de clases de infraestructura
clases <- c("Infraestructura natural", "Infraestructura gris")

# Vector de valores
valores <- c(41, 59)

clases_infraestructura <- 
  data.frame(
    clase = clases, 
    valor = valores
  )

datos <- clases_infraestructura[,c('clase', 'valor')]

fig <- plot_ly(datos, 
               labels = ~clases, 
               values = ~valores, 
               marker = list(
                 colors = c(
                   rgb(43,99,89,  maxColorValue=255),
                   rgb(204,204,204, maxColorValue=255)
                 )
               ),
               type = 'pie')

fig <- fig %>% layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig

```

Row {data-height=200}
-----------------------------------------------------------------------

### Vegetación {.value-box} {data-width=166}
```{r}
valueBox(
  value = "33.8 %", 
  caption = "<h4><strong>% de vegetación</strong></h4><h4><strong>SERVICIO ECOSISTÉMICO DE REGULACIÓN<br>Moderación de extremos del clima</strong></h4>"
)
```

### Vegetación ribereña {.value-box} {data-width=166}
```{r}
valueBox(
  value = "11.8 %", 
  caption = "<h4><strong>% de vegetación ribereña</strong></h4><h4><strong>SERVICIO ECOSISTÉMICO DE SOPORTE<br>Moderación de extremos del clima</strong></h4>"
)
```

### Superficie verde por habitante {.value-box} {data-width=170}
```{r}
valueBox(
  value = "72.9 m2/hab", 
  caption = "<h4><strong>Superficie verde por habitante</strong></h4><h4><strong>SERVICIO ECOSISTÉMICO CULTURAL<br>Beneficios estéticos</strong></h4>"
)
```

### Densidad de cobertura arbórea {.value-box} {data-width=166}
```{r}
valueBox(
  value = "0.31 cobertura/ha", 
  caption = "<h4><strong>Densidad de cobertura arbórea</strong></h4><h4><strong>SERVICIO ECOSISTÉMICO DE SOPORTE<br>Hábitat para la biodiversidad</strong></h4>"
)
```

### Área natural {.value-box} {data-width=166}
```{r}
valueBox(
  value = "31.6 %", 
  caption = "<h4><strong>% de área natural</strong></h4><h4><strong>SERVICIO ECOSISTÉMICO DE SOPORTE<br>Hábitat para la biodiversidad</strong></h4>"
)
```

### Área semi-natural {.value-box} {data-width=166}
```{r}
valueBox(
  value = "26.9 %", 
  caption = "<h4><strong>% de área semi-natural</strong></h4><h4><strong>SERVICIO ECOSISTÉMICO DE SOPORTE<br>Hábitat para la biodiversidad</strong></h4>"
)
```